In [3]:
from qutip import *
import numpy as np
import matplotlib.pyplot as plt

In [22]:
b = destroy(7)

In [23]:
b

Quantum object: dims = [[7], [7]], shape = (7, 7), type = oper, isherm = False
Qobj data =
[[0.         1.         0.         0.         0.         0.
  0.        ]
 [0.         0.         1.41421356 0.         0.         0.
  0.        ]
 [0.         0.         0.         1.73205081 0.         0.
  0.        ]
 [0.         0.         0.         0.         2.         0.
  0.        ]
 [0.         0.         0.         0.         0.         2.23606798
  0.        ]
 [0.         0.         0.         0.         0.         0.
  2.44948974]
 [0.         0.         0.         0.         0.         0.
  0.        ]]

In [28]:
ωb = 5e9*np.pi*2
K = 1e8*np.pi*2

H0 = ωb *b.dag()*b

H = H0 + K*(b.dag() + b)**4

In [29]:
U = (-1j*H0).expm()

In [30]:
U.dag()*H*U

Quantum object: dims = [[7], [7]], shape = (7, 7), type = oper, isherm = False
Qobj data =
[[1.88495559e+09+0.00000000e+00j 0.00000000e+00+0.00000000e+00j
  5.33145953e+09-1.67976643e+04j 0.00000000e+00+0.00000000e+00j
  3.07811959e+09+2.75721056e+04j 0.00000000e+00+0.00000000e+00j
  0.00000000e+00+0.00000000e+00j]
 [0.00000000e+00+0.00000000e+00j 4.08407045e+10-1.45519152e-11j
  0.00000000e+00+0.00000000e+00j 1.53905980e+10+3.62482624e+05j
  0.00000000e+00+0.00000000e+00j 6.88288465e+09+3.53969811e+04j
  0.00000000e+00+0.00000000e+00j]
 [5.33145953e+09+1.67976643e+04j 0.00000000e+00+0.00000000e+00j
  8.73362758e+10-5.82076609e-11j 0.00000000e+00+0.00000000e+00j
  3.04718293e+10+3.68956568e+05j 0.00000000e+00+0.00000000e+00j
  1.19215059e+10+2.88694050e+05j]
 [0.00000000e+00+0.00000000e+00j 1.53905980e+10-3.62482624e+05j
  0.00000000e+00+0.00000000e+00j 1.41371669e+11+0.00000000e+00j
  0.00000000e+00+0.00000000e+00j 5.05786661e+10-9.31125832e+05j
  0.00000000e+00+0.00000000e+00j]
 [3.0

In [31]:
(b**2 + b.dag()**2)/np.sqrt(2)*5.331

Quantum object: dims = [[7], [7]], shape = (7, 7), type = oper, isherm = True
Qobj data =
[[ 0.          0.          5.331       0.          0.          0.
   0.        ]
 [ 0.          0.          0.          9.23356286  0.          0.
   0.        ]
 [ 5.331       0.          0.          0.         13.05822982  0.
   0.        ]
 [ 0.          9.23356286  0.          0.          0.         16.85810221
   0.        ]
 [ 0.          0.         13.05822982  0.          0.          0.
  20.64687422]
 [ 0.          0.          0.         16.85810221  0.          0.
   0.        ]
 [ 0.          0.          0.          0.         20.64687422  0.
   0.        ]]

In [21]:
(b*b.dag())**2

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[ 1.  0.  0.  0.  0.]
 [ 0.  4.  0.  0.  0.]
 [ 0.  0.  9.  0.  0.]
 [ 0.  0.  0. 16.  0.]
 [ 0.  0.  0.  0.  0.]]